### ISSUE TITLE
[Request] Trap focus in RadModal

### ISSUE THREAD

**Issue by aaxelb** [healthsparq/ember-radical#111]
Hello! ember-radical is rad, thanks for building it!

## Summary

RadModal doesn't trap focus -- you can press Tab to move focus behind the overlay and click buttons that shouldn't be so easily available. This is less than ideal for a11y. Is it a feature you'd consider adding?

[Here's an example of a (non-ember) modal library that seems to trap focus well.](https://micromodal.now.sh/)

Edit: [ember-focus-trapper](https://github.com/steveszc/ember-focus-trapper) might make it an easy change

## Description + Repro Steps

1. Open a RadModal modal
2. Press Tab several times, observe focus moving on the page behind the modal
3. Press enter to click buttons that shouldn't be so easy to reach

## Example
Visible in the [ember-radical guide](https://healthsparq.github.io/ember-radical/getting-started/modals). This is me pressing Tab-Enter-Tab-Tab-Tab-Enter-Tab-Tab-... etc. to open a bunch of modals on top of each other (gets harder to see as the background overlays stack):
![focus](https://user-images.githubusercontent.com/6776190/56221066-84439480-6037-11e9-8247-2402cddf8b7f.gif)

## Environment Information
n/a

**Comment by austinezell** [comment]
@aaxelb Good request! That's something we've been meaning to get to. 

It should now be resolved as part of release 2.1.0. I haven't deployed a new version of the demo app yet, so is not testable there. If you find any issues with it, please let us know!
