### ISSUE TITLE
Import only structural styles require variables from skeleton theme

### ISSUE THREAD

**Issue by pmkhoa** [healthsparq/ember-radical#37]
Hi @evrowe,

I got this error when trying to use the add-on with structural styles only.
`Error: Undefined variable: "$alert-padding".`

It seems like `https://github.com/healthsparq/ember-radical/blob/master/app/styles/ember-radical/_component-structures.scss` style depends on `https://github.com/healthsparq/ember-radical/blob/master/app/styles/ember-radical/skeleton-theme/utils/_variables.scss`.

Is it possible to remove that dependency?

Thanks!

**Comment by evrowe** [comment]
@pmkhoa We don't want to remove that dependency outright, however we have #23 logged already to allow users to opt out of using any of our styles.

This seems to me like it's more of an issue with a variable having been stored in the wrong file; structural CSS files shouldn't depend on variables from the theme CSS, so we will move that variable to the appropriate location.

**Comment by evrowe** [comment]
@pmkhoa We've fixed this problem and it's been merged into master. I'm aiming to cut a new pre-release tag before EOD but if you want to just bring in the latest commit from the master branch you can get it right away.
