### ISSUE TITLE
Update Component Namespace to `rad-` (from `core-`)

### ISSUE THREAD

**Issue by evrowe** [healthsparq/ember-radical#44]
## Summary
All component names, their CSS classes, and documentation/example references should have `core-` swapped out for `rad-`.

## Description + Repro Steps
We should update the namespace on these components from `core-` to `rad-` to be more _on brand_ with the name of the addon, and also to make it more specific to our code.

`core-` is a holdover from the `uicore` port and it would be wise to differentiate between the two to avoid confusion internally.

## Example
Currently, we have components like `core-button` and `core-modal`; these would be renamed to `rad-button` and `rad-modal`.

**Comment by bigmoves** [comment]
This is a rad idea
